# Generated by Django 5.2.1 on 2025-05-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('dog', 'Chien'), ('cat', 'Chat'), ('rabbit', 'Lapin')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('weight', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Mâle'), ('female', 'Femelle')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='owners.owner')),
            ],
        ),
    ]
