# Generated by Django 4.2.22 on 2025-06-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
