# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
# Ce fichier permet à Python de reconnaître le répertoire comme un package Python
